import '@/styles/globals.css';

import clsx from 'clsx';
import type { Metadata } from 'next';

import { axiforma } from '@/configs/fonts.configs';

export const metadata: Metadata = {
  title: 'Blog.dev | Where you can sharing, stay up-to-date and grow their careers',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={clsx(axiforma.variable, 'font-axiforma')}>{children}</body>
    </html>
  );
}
